[package]
name = "bind_group"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive = { path = "derive"}
wgpu = "0.18"

[dev_dependencies]
pollster = "0.3"

[[test]]
name = "buffer"
path = "tests/buffer.rs"
